boottestRuner: Fix call to failnotify
The wrong arguments in the call to failnotify are causing the
java.lang.NoSuchMethodError. Remove the wrong "global" argument.

Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>
Signed-off-by: Anna-Maria Gleixner <anna-maria@linutronix.de>