boottestRunner: Catch errors in postprocessing
The postprocessing of boottest results may fail and raising an
exception. Catching the exception in boottest to print out
informations about the failure is to late, because the context is lost:

hudson.model.Hudson
boottest failed:
java.io.NotSerializableException: hudson.model.Hudson
hudson.model.Hudson
[Ljava.lang.StackTraceElement;@47043b5f
boottest failed.

Catch these exceptions in BoottestRunner, print out informations about
the failure and raise an error to inform upstream.

Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>
Signed-off-by: Anna-Maria Gleixner <anna-maria@linutronix.de>