Remove package scope from global variables
The CPS groovy class loader gets confused while loading global
variables with explicit declared package scope:

java.lang.LinkageError: loader (instance of  org/jenkinsci/plugins/workflow/cps/CpsGroovyShell$CleanGroovyClassLoader): attempted  duplicate class definition for name: "de/linutronix/lib4lib/shunit"

Different Scripts tries to initialise the same global variable and fail
on the second try.

Due to the loss of package scope the helper class needs to be imported.
This need a rename of the the variable name helper due an import is a
global name and a use of the variable name helper ends up in a declaration
of different type.

Remove the package scope from global variables and explicit import the
missing classes.

Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Signed-off-by: Anna-Maria Gleixner <anna-maria@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>